name: React-CI
 
on:
  push:
    branches:
      - "master"
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      martix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test